### ISSUE TITLE
[Suggestion] Hide 2/3/4* and individual units

### ISSUE THREAD

**Issue by Midnight08** [zklm/ssherder-issues#10]
Adding lower star units is important for chains, Additionally some units are used up for ST but still part of chains. The Ability to hide them from the character page would allow one to better use this to show a collection (like for team help), as well as to just sort through one's own collection. 

Most of the time we couldn't care less about which 2*'s we have, but in order for chains to populate correctly we have to add them. The ability to filter these things out would make things much easier.

My suggestion is 2 phase
1) A Filter Toggle for each rarity. Checkbox based, Select 2/3/4 and they disappear until you uncheck them. 

2) An on character edit page option to "force Filter" This will remove them from the page UNLESS

3) an additional Filter for individual filtered items - which will show those who you have filtered (For example, if you collect a new copy and want to update the existing one)

So as shown below
1st is the tier filter (Multiple selections allowed)
Tier Filter
6
5
4
3
2

2nd is the Individual Filter (one or the other)
Show Individual Filtered
Hide Individual Filtered

Thanks
-NighstX / ReyT

**Comment by zklm** [comment]
Definitely, I really should've finished up on filters before releasing but for some reason just stopped at sorting. 

> Most of the time we couldn't care less about which 2*'s we have, but in order for chains to populate correctly we have to add them.

This however is another issue. I took a bit of a lazy path for handling chain eligibility, it really shouldn't be calculating it based on the characters a user has in their character box because ideally the character box is for managing the characters they currently have. However, to track chain eligibility, users will also be adding characters they once had because that's how chains work.

When the Character Book section comes out, that'll allow users to track ownership of characters and hopefully a button to bulk-set ownership of characters based on the ones they have in their character box. After that, I'll probably provide a setting for users to choose how to determine chain eligibility, which would either be from the characters they have in character box, or the proper way from the character ownership status

**Comment by Midnight08** [comment]
Awesome, Lots of work for a personal passion, I will await updates patiently, and, while broke atm, if im doing better when donations open, i will be sending one. 

Great work - im promoting it for you as much as i can,

**Comment by zklm** [comment]
Filtering is added.

However, regarding suggestion 2) and 3), I think using the "priority" field of each user character should be used for filtering rather than a specific option for each one just to filter it. Filtering currently supports:

 - Element 
 - Category
 - Role
 - Stone Slots
 - Priority
 - Rarity
 - Gender
 - Season
 - Name
 - Note

Clicking 'Save as default' will save the current filtering options to localStorage, so customized filters will automatically load when revisiting. The filtering options are also appended to the URI (after the #), the order of the options follow the same order as the list above. e.g. "#31,7,63,31,15,eq,0,3,3,,;default,0" (element option has 5 items meaning 31 possible combinations, 31 in this case represents all, or none rather, 2 would represent checking only the thunder checkbox). 

Anyway, with the filtering and sorting options appended the URL you can also share the link with others this way if you want to. About donations, they should be up within a week but if you're broke don't worry about it unless you really want to. The site only has a few hundred users so the server costs are currently low, so it's not like I'm extremely desperate for them, though I am humbled by the thought that you'd want to donate!

In the future I'll expand on filtering, allowing for things like filtering by evolution eligibility/status, chain eligibility/completion status, skill effect filtering, etctera, but right now there's more important things I need to do.
