### ISSUE TITLE
Active pass and active skills?

### ISSUE THREAD

**Issue by Relunx** [zklm/ssherder-issues#26]
Hi!

It seems the damage formula is not adding/calculating active skills for example Milky Way Active.
Second, maybe just me but I didn't see/how to set a dmg calculator on an active pass.

**Comment by zklm** [comment]
Heyo.

Both aren't finished yet. All actives aside from pass, long pass and target skills should work in 1-3 days, just sorting out a lot of bugs and inconsistencies. The skill effect itself is [simple](http://i.imgur.com/tX9TnYM.png), the main issues have been:

- tying regular actives with active skills which can accumulate or have a counter (different to accumulating skills, things like shields which have N uses)
- properly handling skill effect removal and additions when characters get modified, this damage simulator has to go a bit beyond how battles work in the game, because in the game a character can't be modified during the battle itself which means a lot of skill data can be set pre-battle during initialization (things like setting ace skill on all players, role skills, etc), unfortunately the damage simulator is doing something close to that initialization step when a character is modified, right now I'm working on it having it clear only the skills of the modified character (includes having to check all other characters and checking if the effect was sourced from the modified character), then it'll be able to preserve things like active skill buffs and current stack level of accumulating skills on other characters

Blah, anyway, will make a news post about this on Thursday when game data updates.

**Comment by zklm** [comment]
Partially added actives.

Now another problem is characters losing a few types of skill effects sourced by other characters whenever they're edited.
