### ISSUE TITLE
Can't find AU96 Karpilla?

### ISSUE THREAD

**Issue by kagenin** [zklm/ssherder-issues#6]
Is Karpilla's icon not up there in the chain calculator, or am I blind?

**Comment by zklm** [comment]
I've been a bit lazy with the chain calculator, it doesn't have any characters released in March, April and May (about two or three characters). Should be updated soon.

**Comment by zklm** [comment]
Added Crocell, Askeladd, Lindberg, Karpila and Irru.

Though I don't expect to regularly do chain calculator updates (will be 1-2 months) because really, the point of the new site was to be able to permanently and reliably track this sort of stuff, using the browser's localStorage for the chain calculator is a bit silly because it's very easy to lose all the data (using a different browser, using a different device, etc), but my choices were limited back then. And also, new characters typically aren't found in any chains of other characters until months later.
