### ISSUE TITLE
Can use the same unit multiple times in formation maker

### ISSUE THREAD

**Issue by theabhishek2511** [zklm/ssherder-issues#9]
i kind of did this on accident but in hindsight it's hilarious : https://ssherder.com/users/omgitsnewton/formations/#110

**Comment by zklm** [comment]
I couldn't bother coming up with a nice way to validate uniqueness of characters in formations, so for now it's allowed.

Though I'll probably change it on the frontend so that when a user character has been selected, that user character will be removed from the list of searchable characters on other positions.
